"""
Plan Model for Project Astra.
Represents a structured execution plan generated by Astra's Planner Engine.
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import List, Dict, Any, Optional
import time
import uuid

from app.models.goal import Goal
from app.models.plan_step import PlanStep, StepStatus


class PlanStatus(str, Enum):
    DRAFT = "draft"
    VALIDATED = "validated"
    EXECUTING = "executing"
    COMPLETED = "completed"
    FAILED = "failed"
    REJECTED = "rejected"


@dataclass
class Plan:
    """
    Complete execution plan with ordered steps, validation status, and execution logs.
    """
    goal: Goal
    steps: List[PlanStep] = field(default_factory=list)
    plan_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    status: PlanStatus = PlanStatus.DRAFT
    created_at: float = field(default_factory=time.time)
    execution_logs: List[str] = field(default_factory=list)

    @property
    def is_complete(self) -> bool:
        return all(s.status == StepStatus.SUCCESS for s in self.steps)

    @property
    def has_failures(self) -> bool:
        return any(s.status == StepStatus.FAILED for s in self.steps)

    def add_log(self, message: str) -> None:
        timestamp_str = time.strftime("%H:%M:%S")
        self.execution_logs.append(f"[{timestamp_str}] {message}")

    def to_dict(self) -> Dict[str, Any]:
        return {
            "plan_id": self.plan_id,
            "goal": self.goal.to_dict(),
            "status": self.status.value if isinstance(self.status, PlanStatus) else self.status,
            "steps": [s.to_dict() for s in self.steps],
            "created_at": self.created_at,
            "execution_logs": self.execution_logs
        }
